import React from "react";
import Navigation from "@/components/Navigation";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  metadataBase: new URL('http://localhost:3000'),
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html>
      <body>
          <div>
            <Navigation />
          </div>
          <div>
            {/* {data.data} */}
            {children}
        </div>
      </body>
    </html>
  );
}
